name: Build piRa1n-OS

on:
  push:
    paths:
    - 'version'

env:
  VERSION: "$(<version)"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build piRa1n-OS
      run: |
        sudo apt-get install git coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl bc -y
        sudo ./build.sh
        sudo mv /home/debian/piRa1n-OS/work/*-*-*-piRa1n-OS/export-image/*-*-*-piRa1n-OS-lite.img *-*-*-piRa1n-OS.img
        bzip2 -9 *-*-*-piRa1n-OS.img

    - name: Generate ReleaseNotes.md
      run: |
        echo "- piRa1n v$(curl -sk https://raw.githubusercontent.com/raspberryenvoie/piRa1n/master/version)" >> ReleaseNotes.md
        echo "- piRa1n-web v$(curl -sk https://raw.githubusercontent.com/raspberryenvoie/piRa1n-web/master/version)" >> ReleaseNotes.md
        echo '**SHA-256:**' >> ReleaseNotes.md
        sha256sum *-*-*-piRa1n-OS.img.bz2 >> ReleaseNotes.md
        cat ReleaseNotes.md

    - name: Publish GitHub Release
      uses: ncipollo/release-action@v1
      with:
        name:: "piRa1n-OS ${{ env.VERSION }}"
        bodyFile: ReleaseNotes.md
        artifacts: "*-*-*-piRa1n-OS.img"
        tag: ${{ env.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
